spring:
  application:
    name: user
  mail:
    host: smtp.163.com
    username: a2698360477@163.com
    password: RBcBvBtDDRFR7WXF
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zafunity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true
server:
  port: 1222
  servlet:
    context-path: /api/user
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0