spring:
  application:
    name: service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zafunity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 1224
  servlet:
    context-path: /api/service
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0