spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:1222/api/user
          predicates:
            - Path=/api/user/**
            - Method=GET,POST,PUT,DELETE
        - id: post
          uri: http://localhost:1223/api/post
          predicates:
            - Path=/api/post/**
            - Method=GET,POST,PUT,DELETE
  main:
    web-application-type: reactive
server:
  port: 1221
  servlet:
    context-path: /api/gateway