spring:
  application:
    name: gateway
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zafunity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:1222/api/user
          predicates:
            - Path=/api/user/**
            - Method=GET,POST,PUT,DELETE
        - id: post
          uri: http://localhost:1223/api/post
          predicates:
            - Path=/api/post/**
            - Method=GET,POST,PUT,DELETE
  main:
    web-application-type: reactive
server:
  port: 1221
  servlet:
    context-path: /api/gateway

# 聚合文档
knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式
    strategy: manual
    routes:
      - name: 用户服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /user/v2/api-docs?group=default
        service-name: user
        # 路由前缀
        context-path: /api/user
        order: 2
      - name: 帖子服务
        url: /post/v2/api-docs?group=default
        service-name: order-service
        # 路由前缀
        context-path: /api/post
        order: 3
